seed: 42

config_name: base_config

data:
  path: "data/train_data.txt"
  validation_split_percentage: 10
  mlm_probability: 0.15

tokenizer: 
  name: bert-base-uncased
  max_length: 512

model:
  name: bert-base-uncased

training:
  output_dir: saved_models
  num_train_epochs: 1
  save_total_limit: 2
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  evaluation_strategy: "steps"
  save_strategy: "steps"
  warmup_steps: 500
  weight_decay: 0.01
  logging_dir: "logs"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
